version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: udigo-backend
    command: "python manage.py runserver 0.0.0.0:8000"
    ports: 
      - "8000:8000"
    restart: unless-stopped
    volumes:
    - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.28
    container_name: udigo-db
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    volumes:
    - mysql-data:/var/lib/mysql
    ports:
      - "33066:3306"

  ml:
    build:
      context: ../UDIGO_INFERENCE_SERVER/
      dockerfile: ../UDIGO_INFERENCE_SERVER/Dockerfile
    container_name: udigo-ai
    command: "uvicorn app.main:app --reload --host=0.0.0.0 --port=5050"
    ports:
      - "5050:5050"
    restart: unless-stopped
    volumes:
      - ../UDIGO_INFERENCE_SERVER/:/app

volumes:
  mysql-data: {}
