version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: udigo-backend
    command: "python manage.py runserver"
    ports: 
      - "8000:8000"
    restart: unless-stopped
    volumes:
    - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    container_name: udigo-db
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
    volumes:
    - mysql-data:/var/lib/mysql
    ports:
      - "33066:3306"

volumes:
  mysql-data: {}
