name: Django CI

on:
  push:
    branches: [test/actions]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5.7.22
        environment:
          MYSQL_DATABASE: admin
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
        ports:
          - "3306:3306"
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          pytest
