name: Django CI

on:
  push:
    branches: [test/actions]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Create .env File
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_KAKAO_REDIRECT_URI: ${{ secrets.KAKAO_REDIRECT_URI }}
          envkey_KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
          envkey_KAKAO_SECRET_KEY: ${{ secrets.KAKAO_SECRET_KEY }}
      - name: Mysql Setup
        uses: gtadam/mysql-deploy-action@v1
        with:
          DATABASE_HOST: "localhost"
          DATABASE_PORT: "3306"
          DATABASE_NAME: "admin"
          DATABASE_USERNAME: "root"
          DATABASE_PASSWORD: "root"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          mkdir logs
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          pytest
