name: Push to Docker hub registry

on:
  push:
    branches: 
    - main 
    paths-ignore:
    - '.gitignore'
    - '**.md'
    - '**.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Build and Push to Docker Hub
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: minchae3618/udigo-backend-drf
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: latest
